<script>
    // exception handling :-
    let a = 12;
    let b = 7;
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    try {
        console.log("sum = ", a + c);
    }
    catch(excep)
    {
        console.log(excep);
        console.log("some error is occured");
    }
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
</script>